image: Visual Studio 2017
configuration: Release
before_build:
- cmd: Nuget restore
build:
  project: WeChatLogin.sln
  verbosity: minimal

after_build:
- dotnet pack "WeChatLogin" -c %CONFIGURATION% --no-build -o artifacts

artifacts:
- path: \**\artifacts\**\*.*
  
cache:
- '%USERPROFILE%\.nuget\packages'
on_finish: # Done